const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
const CREATE_CATEGORY = "CREATE_CATEGORY";
const GET_ERROR = "GET_ERROR";
const LIMIT_CATEGORY = 5;

export { GET_ALL_CATEGORY, CREATE_CATEGORY, GET_ERROR, LIMIT_CATEGORY };
